server:
  port: 9002
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
#        server-addr: 192.168.56.193:8848 #单机
        server-addr: 192.168.56.194:8849 #集群
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'